#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
#ifndef CYGNUSUI_SWIFT_H
#define CYGNUSUI_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebRTC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CygnusUI",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class UISearchBar;
@class UITableView;
@class UIButton;
@class NSLayoutConstraint;
@class NSString;
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC8CygnusUI30AvailableDevicesViewController")
@interface AvailableDevicesViewController : UIViewController
@property (nonatomic, weak) IBOutlet UISearchBar * _Null_unspecified searchBar;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified sortButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified reachButton;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified bottomConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (IBAction)sortButtonTapped:(id _Nonnull)sender;
- (IBAction)reachButtonTapped:(id _Nonnull)sender;
- (IBAction)closeButtonTapped:(id _Nonnull)sender;
- (void)reloadDevices;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class UITextField;

@interface AvailableDevicesViewController (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end


@interface AvailableDevicesViewController (SWIFT_EXTENSION(CygnusUI)) <UISearchBarDelegate>
- (void)searchBar:(UISearchBar * _Nonnull)searchBar textDidChange:(NSString * _Nonnull)searchText;
@end

@class NSIndexPath;
@class UITableViewCell;

@interface AvailableDevicesViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8CygnusUI21BitfieldTableViewCell")
@interface BitfieldTableViewCell : UITableViewCell
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC8CygnusUI22BitfieldViewController")
@interface BitfieldViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified tableViewHeight;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified writeButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (IBAction)cancelButtonTapped:(id _Nonnull)sender;
- (IBAction)writeValueTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface BitfieldViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didDeselectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


@class NSTextContainer;

SWIFT_CLASS("_TtC8CygnusUI12ChatTextView")
@interface ChatTextView : UITextView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame textContainer:(NSTextContainer * _Nullable)textContainer SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8CygnusUI12CircleButton")
@interface CircleButton : UIButton
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIStoryboardSegue;

/// A <code>UIViewController</code> that connects to a device on view load
SWIFT_CLASS("_TtC8CygnusUI27ConnectDeviceViewController")
@interface ConnectDeviceViewController : UIViewController
- (void)viewDidLoad;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
/// @objc target for Selector use. Calls the reconnect function in a <code>Task</code>
- (void)initiateReconnect;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UILabel;

IB_DESIGNABLE
SWIFT_CLASS("_TtC8CygnusUI25ConnectionStatusIndicator")
@interface ConnectionStatusIndicator : UIView
@property (nonatomic) IBInspectable BOOL includeLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified statusView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified statusLabel;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC8CygnusUI10DragHandle")
@interface DragHandle : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIImageView;

/// View controller presented after taking a screenshot or video snippet. Allows user to preview media before sending to peer
SWIFT_CLASS("_TtC8CygnusUI26MediaPreviewViewController")
@interface MediaPreviewViewController : UIViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified screenshotImageView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified containerView;
@property (nonatomic, weak) IBOutlet CircleButton * _Null_unspecified sendButton;
@property (nonatomic, weak) IBOutlet CircleButton * _Null_unspecified closeButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (void)viewDidLoad;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (IBAction)sendButtonTapped:(id _Nonnull)sender;
- (IBAction)closeButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


IB_DESIGNABLE
SWIFT_CLASS("_TtC8CygnusUI13OutlineButton")
@interface OutlineButton : UIButton
@property (nonatomic) IBInspectable BOOL customBorderColor;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@class UIStackView;
@class UISwitch;
@class UICollectionViewLayoutAttributes;

SWIFT_CLASS("_TtC8CygnusUI27ParameterCollectionViewCell")
@interface ParameterCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterNameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterIdLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterDescriptionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterTypeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterBoundsLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified sendButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified sendActivityIndicator;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified dropdownIcon;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified extraInfoStackView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified extraInfoDivider;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified parameterTextField;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified parameterSwitchContainer;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified parameterSwitch;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified parameterSwitchActivityIndicator;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (IBAction)sendButtonTapped:(id _Nonnull)sender;
- (IBAction)parameterSwitchValueChanged:(id _Nonnull)sender;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ParameterCollectionViewCell (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
@end

@class UIPickerView;

@interface ParameterCollectionViewCell (SWIFT_EXTENSION(CygnusUI)) <UIPickerViewDataSource, UIPickerViewDelegate>
- (NSInteger)numberOfComponentsInPickerView:(UIPickerView * _Nonnull)pickerView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)pickerView:(UIPickerView * _Nonnull)pickerView numberOfRowsInComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)pickerView:(UIPickerView * _Nonnull)pickerView titleForRow:(NSInteger)row forComponent:(NSInteger)component SWIFT_WARN_UNUSED_RESULT;
- (void)pickerView:(UIPickerView * _Nonnull)pickerView didSelectRow:(NSInteger)row inComponent:(NSInteger)component;
@end


SWIFT_CLASS("_TtC8CygnusUI29PasswordEntryDialogController")
@interface PasswordEntryDialogController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dialogView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified passwordEntry;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI13PrimaryButton")
@interface PrimaryButton : UIButton
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


SWIFT_CLASS("_TtC8CygnusUI26ReachServiceViewController")
@interface ReachServiceViewController : UIViewController
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI22ReachCLIViewController")
@interface ReachCLIViewController : ReachServiceViewController
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified cliTextView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cliInput;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cliSendButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified cliActivityIndicator;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cliBottomConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (IBAction)cliSendButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNotification;

@interface ReachCLIViewController (SWIFT_EXTENSION(CygnusUI))
- (void)keyboardNotificationWithNotification:(NSNotification * _Nonnull)notification;
@end


@interface ReachCLIViewController (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8CygnusUI25ReachCommandTableViewCell")
@interface ReachCommandTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified commandButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (IBAction)commandButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI27ReachCommandsViewController")
@interface ReachCommandsViewController : ReachServiceViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachCommandsViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end

@class UIScrollView;
@class UISlider;

SWIFT_CLASS("_TtC8CygnusUI29ReachDiagnosticViewController")
@interface ReachDiagnosticViewController : ConnectDeviceViewController
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified deviceStackView;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified loadingStackView;
@property (nonatomic, weak) IBOutlet UIScrollView * _Null_unspecified reachScrollView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified debugContainer;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified debugTextView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified debugFormatOptionsView;
@property (nonatomic, weak) IBOutlet UISlider * _Null_unspecified fontSizeSlider;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified cliContainer;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified cliTextView;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified cliInput;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cliSendButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified cliActivityIndicator;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified cliBottomConstraint;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified pingNumTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified pingLengthTextField;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified pingButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified readFileButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified readOffsetTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified readLengthTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified readAckRateTextField;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified readActivityIndicator;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified writeFileButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified writeOffsetTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified writeLengthTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified writeAckRateTextField;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified writeActivityIndicator;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified sendCommandButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified connectWifiButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified ssidTextField;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified passwordTextField;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified disconnectWifiButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified ssidTextFieldDisconnect;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)keyboardNotificationWithNotification:(NSNotification * _Nonnull)notification;
- (void)debugViewButtonTapped;
- (void)terminalButtonTapped;
- (IBAction)getDeviceInfoButtonTapped:(id _Nonnull)sender;
- (IBAction)discoverParametersButtonTapped:(id _Nonnull)sender;
- (IBAction)pingButtonTapped:(id _Nonnull)sender;
- (IBAction)fileDescriptorsButtonTapped:(id _Nonnull)sender;
- (void)readFileButtonTapped;
- (void)writeFileButtonTapped;
- (IBAction)discoverCommandsButtonTapped:(id _Nonnull)sender;
- (void)commandButtonTapped;
- (IBAction)getTimeButtonTapped:(id _Nonnull)sender;
- (IBAction)discoverWifiButtonTapped:(id _Nonnull)sender;
- (IBAction)connectWifiButtonTapped:(id _Nonnull)sender;
- (IBAction)disconnectWifiButtonTapped:(id _Nonnull)sender;
- (IBAction)sliderValueChanged:(id _Nonnull)sender;
- (IBAction)clearTextButtonTapped:(id _Nonnull)sender;
- (IBAction)expandButtonTapped:(id _Nonnull)sender;
- (IBAction)cliSendButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachDiagnosticViewController (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end

@class UIProgressView;
@class UIDocumentPickerViewController;
@class NSURL;

SWIFT_CLASS("_TtC8CygnusUI29ReachFileAccessViewController")
@interface ReachFileAccessViewController : ReachServiceViewController <UIDocumentPickerDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified listActivityIndicator;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified listHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified detailsContainer;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified downloadFileButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified uploadFileButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileIdLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileNameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileAccessLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileSizeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileStorageLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileMaxSizeLabel;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified fileMaxSizeContainer;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified uploadButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified selectFileButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified transferContainer;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileTransferActionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileUploadingNameLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified transferCompletionCheckmark;
@property (nonatomic, weak) IBOutlet UIProgressView * _Null_unspecified transferProgressView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified fileTransferSizeLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cancelButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified doneButton;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)backButtonTapped:(id _Nonnull)sender;
- (IBAction)downloadFileButtonTapped:(id _Nonnull)sender;
- (IBAction)uploadFileButtonTapped:(id _Nonnull)sender;
- (IBAction)selectFileButtonTapped:(id _Nonnull)sender;
- (IBAction)uploadButtonTapped:(id _Nonnull)sender;
- (IBAction)cancelButtonTapped:(id _Nonnull)sender;
- (IBAction)doneButtonTapped:(id _Nonnull)sender;
- (void)documentPicker:(UIDocumentPickerViewController * _Nonnull)controller didPickDocumentsAtURLs:(NSArray<NSURL *> * _Nonnull)urls;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachFileAccessViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8CygnusUI32ReachFileDescriptorTableViewCell")
@interface ReachFileDescriptorTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified idLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified storageLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI27ReachInfoCollectionViewCell")
@interface ReachInfoCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet ConnectionStatusIndicator * _Null_unspecified connectionStatusIndicator;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified expandIcon;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified extraInfoDivider;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified extraInfoStackView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified manufacturerLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified firmwareLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified deviceDescriptionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified protocolVersionLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified servicesLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterHashLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified maxMessageSizeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified bigDataBufferSizeLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified parameterBufferCountLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified numParamsInResponseLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified deviceDescriptionLengthLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified maxParamBytesLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified paramInfoDescriptionLengthLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified mediumStringLengthLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified shortStringLengthLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified numDescriptorsInResponseLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified numParamNotificationsLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified numCommandsInResponseLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified countParamDescInResponseLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified paramNotifyConfigCountLabel;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UICollectionView;

SWIFT_CLASS("_TtC8CygnusUI29ReachParametersViewController")
@interface ReachParametersViewController : ReachServiceViewController
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (IBAction)refreshButtonTapped:(id _Nonnull)sender;
- (void)keyboardWillShow:(NSNotification * _Nonnull)notification;
- (void)keyboardWillHide:(NSNotification * _Nonnull)notification;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachParametersViewController (SWIFT_EXTENSION(CygnusUI)) <UICollectionViewDataSource, UICollectionViewDelegate>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8CygnusUI30ReachServiceCollectionViewCell")
@interface ReachServiceCollectionViewCell : UICollectionViewCell
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified icon;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
- (UICollectionViewLayoutAttributes * _Nonnull)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes * _Nonnull)layoutAttributes SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC8CygnusUI23ReachTimeViewController")
@interface ReachTimeViewController : ReachServiceViewController <UIDocumentPickerDelegate>
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified utcCurrentLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified rawLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified nonTimezonedView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified localLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified utcLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified deviceLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified timezonedView;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)utcButtonTapped:(id _Nonnull)sender;
- (IBAction)localButtonTapped:(id _Nonnull)sender;
- (IBAction)refreshButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIBarButtonItem;

SWIFT_CLASS("_TtC8CygnusUI19ReachViewController")
@interface ReachViewController : ConnectDeviceViewController
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified loadingStackView;
@property (nonatomic, weak) IBOutlet UICollectionView * _Null_unspecified collectionView;
@property (nonatomic, weak) IBOutlet UIBarButtonItem * _Null_unspecified moreBarButtonItem;
@property (nonatomic, weak) IBOutlet UIView * _Nullable sessionButtonContainer;
@property (nonatomic, weak) IBOutlet UIButton * _Nullable sessionButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (IBAction)supportButtonTapped:(id _Nonnull)sender;
- (IBAction)showMenuItems;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachViewController (SWIFT_EXTENSION(CygnusUI)) <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
- (NSInteger)collectionView:(UICollectionView * _Nonnull)collectionView numberOfItemsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UICollectionViewCell * _Nonnull)collectionView:(UICollectionView * _Nonnull)collectionView cellForItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)collectionView:(UICollectionView * _Nonnull)collectionView didSelectItemAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end


SWIFT_CLASS("_TtC8CygnusUI22ReachWiFiTableViewCell")
@interface ReachWiFiTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified connectedLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified nameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified securityLabel;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI23ReachWiFiViewController")
@interface ReachWiFiViewController : ReachServiceViewController
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified titleLabel;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified backButton;
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified listActivityIndicator;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified listHeader;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified detailsContainer;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified connectButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified disconnectButton;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified wifiNameLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified wifiConnectedLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified wifiSignalStrengthLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified wifiSecurityLabel;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified wifiBandLabel;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified autoconnectContainer;
@property (nonatomic, weak) IBOutlet UISwitch * _Null_unspecified autoconnectSwitch;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (IBAction)cancelButtonTapped:(id _Nonnull)sender;
- (IBAction)backButtonTapped:(id _Nonnull)sender;
- (IBAction)connectButtonTapped;
- (IBAction)disconnectButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface ReachWiFiViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (UIView * _Nullable)tableView:(UITableView * _Nonnull)tableView viewForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForHeaderInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITouch;
@class UIEvent;

SWIFT_CLASS("_TtC8CygnusUI26SetupSupportViewController")
@interface SetupSupportViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified pinTextField;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified continueButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified bottomConstraint;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified remoteSupportImageView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified hostButton;
@property (nonatomic, weak) IBOutlet UIBarButtonItem * _Null_unspecified contextMenuButton;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end




@interface SetupSupportViewController (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textFieldShouldClear:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8CygnusUI24SupportChatTableViewCell")
@interface SupportChatTableViewCell : UITableViewCell
@property (nonatomic, weak) IBOutlet ChatTextView * _Nullable messageLabel;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable messageImageView;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable imageViewWidthConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable imageViewHeightConstraint;
@property (nonatomic, weak) IBOutlet UIView * _Nullable videoContainerView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable videoHeightConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Nullable videoWidthConstraint;
@property (nonatomic, weak) IBOutlet UIImageView * _Nullable videoPlayImageView;
- (void)awakeFromNib;
- (void)setSelected:(BOOL)selected animated:(BOOL)animated;
- (void)toggleVideo;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=3.0);
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI25SupportChatViewController")
@interface SupportChatViewController : UIViewController
@property (nonatomic, weak) IBOutlet UITableView * _Null_unspecified tableView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified noMessageView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified bottomConstraint;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified sendButton;
@property (nonatomic, weak) IBOutlet UITextField * _Null_unspecified chatTextField;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified sendActivityIndicator;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified cameraButton;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified mediaViewHeightConstraint;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified mediaImageView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified mediaImageViewWidth;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified mediaViewSpacerHeightConstraint;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified mediaImageViewHeightComparisonConstraint;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)didReceiveMemoryWarning;
- (IBAction)sendButtonTapped:(id _Nonnull)sender;
- (IBAction)cameraButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@interface SupportChatViewController (SWIFT_EXTENSION(CygnusUI))
- (void)keyboardNotificationWithNotification:(NSNotification * _Nonnull)notification;
@end


@interface SupportChatViewController (SWIFT_EXTENSION(CygnusUI)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end


@interface SupportChatViewController (SWIFT_EXTENSION(CygnusUI)) <UITableViewDataSource, UITableViewDelegate>
- (NSInteger)numberOfSectionsInTableView:(UITableView * _Nonnull)tableView SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView willDisplayCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didEndDisplayingCell:(UITableViewCell * _Nonnull)cell forRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UIImagePickerController;

@interface SupportChatViewController (SWIFT_EXTENSION(CygnusUI)) <UIImagePickerControllerDelegate, UINavigationControllerDelegate>
- (void)imagePickerControllerDidCancel:(UIImagePickerController * _Nonnull)picker;
- (void)imagePickerController:(UIImagePickerController * _Nonnull)picker didFinishPickingMediaWithInfo:(NSDictionary<UIImagePickerControllerInfoKey, id> * _Nonnull)info;
@end


SWIFT_CLASS("_TtC8CygnusUI27SupportDeviceViewController")
@interface SupportDeviceViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified inactiveView;
@property (nonatomic, weak) IBOutlet UITextView * _Null_unspecified logTextView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified deviceButton;
- (void)viewDidLoad;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (IBAction)deviceButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI28SupportOptionsViewController")
@interface SupportOptionsViewController : UIViewController
- (void)viewDidLoad;
- (IBAction)endSupportButtonTapped:(id _Nonnull)sender;
- (IBAction)deviceButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI32SupportReconnectDialogController")
@interface SupportReconnectDialogController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified dialogView;
- (void)viewDidLoad;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CygnusUI32SupportScreenShareViewController")
@interface SupportScreenShareViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified inactiveView;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified activeView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified shareButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified endButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
- (void)viewDidLoad;
- (IBAction)shareButtonTapped:(id _Nonnull)sender;
- (IBAction)endButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol UIViewControllerTransitionCoordinator;

SWIFT_CLASS("_TtC8CygnusUI28SupportSessionViewController")
@interface SupportSessionViewController : UITabBarController
@property (nonatomic, weak) IBOutlet UIBarButtonItem * _Null_unspecified minimizeButton;
@property (nonatomic, weak) IBOutlet UIBarButtonItem * _Null_unspecified moreBarButton;
@property (nonatomic, weak) IBOutlet ConnectionStatusIndicator * _Null_unspecified deviceStatusIndicator;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (IBAction)minimizeTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIPresentationController;
@class UITraitCollection;

@interface SupportSessionViewController (SWIFT_EXTENSION(CygnusUI)) <UIPopoverPresentationControllerDelegate>
- (UIModalPresentationStyle)adaptivePresentationStyleForPresentationController:(UIPresentationController * _Nonnull)controller traitCollection:(UITraitCollection * _Nonnull)traitCollection SWIFT_WARN_UNUSED_RESULT;
@end

@class RTCMTLVideoView;

SWIFT_CLASS("_TtC8CygnusUI26SupportVideoViewController")
@interface SupportVideoViewController : UIViewController
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified inactiveView;
@property (nonatomic, weak) IBOutlet RTCMTLVideoView * _Null_unspecified activeView;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified shareButton;
@property (nonatomic, weak) IBOutlet UIButton * _Null_unspecified endButton;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified activityIndicator;
@property (nonatomic, weak) IBOutlet UIActivityIndicatorView * _Null_unspecified cameraActivityIndicator;
@property (nonatomic, weak) IBOutlet UIStackView * _Null_unspecified cameraButtons;
@property (nonatomic, weak) IBOutlet UIImageView * _Null_unspecified drawImageView;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified drawImageViewWidth;
@property (nonatomic, weak) IBOutlet NSLayoutConstraint * _Null_unspecified drawImageViewHeight;
@property (nonatomic, weak) IBOutlet CircleButton * _Null_unspecified switchCameraButton;
@property (nonatomic, weak) IBOutlet CircleButton * _Null_unspecified screenshotButton;
@property (nonatomic, weak) IBOutlet CircleButton * _Null_unspecified screenRecordButton;
@property (nonatomic, weak) IBOutlet UIView * _Null_unspecified recordingView;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified recordingTimeLabel;
- (void)viewDidLoad;
- (void)prepareForSegue:(UIStoryboardSegue * _Nonnull)segue sender:(id _Nullable)sender;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (IBAction)shareButtonTapped:(id _Nonnull)sender;
- (IBAction)endButtonTapped:(id _Nonnull)sender;
- (IBAction)switchCameraTapped:(id _Nonnull)sender;
- (IBAction)screenshotButtonTapped:(id _Nonnull)sender;
- (IBAction)screenRecordButtonTapped:(id _Nonnull)sender;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@protocol RTCVideoRenderer;

@interface SupportVideoViewController (SWIFT_EXTENSION(CygnusUI)) <RTCVideoViewDelegate>
- (void)videoView:(id <RTCVideoRenderer> _Nonnull)videoView didChangeVideoSize:(CGSize)size;
@end


SWIFT_CLASS("_TtC8CygnusUI14TextViewLogger")
@interface TextViewLogger : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface TextViewLogger (SWIFT_EXTENSION(CygnusUI)) <UITextViewDelegate>
- (void)scrollViewDidScroll:(UIScrollView * _Nonnull)scrollView;
@end












@class UIColor;

@interface UIView (SWIFT_EXTENSION(CygnusUI))
@property (nonatomic, strong) IBInspectable UIColor * _Nullable borderColor;
@end


@class RTCVideoFrame;

/// A helper class to render screenshots and video snippets from a WebRTC stream source
SWIFT_CLASS("_TtC8CygnusUI13VideoRecorder")
@interface VideoRecorder : NSObject <RTCVideoRenderer>
- (void)renderFrame:(RTCVideoFrame * _Nullable)frame;
- (void)setSize:(CGSize)size;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
